feat: add support for .NET8.0
speakeasy-api/sdk-generation-action pull request #130
Opened 2024-05-16 15:42 UTC by 2ynn

install .NET8.0 alongside .NET5.0 and .NET6.0

2024-05-16 16:11 UTC, idbentley requested changes
I think this PR is a little bit incomplete:  I would expect that there would also be changes to the `compileCommand`, to the version check in `config.ts` for csharp, and possibly changing one of the test `gen.yaml` files to run against dotnet8

https://github.com/speakeasy-api/openapi-generation/blob/main/templates/templates/csharp/compile.ts

2024-05-16 16:41 UTC, 2ynn commented
@idbentley I will keep this PR as draft until [PR#1264](https://github.com/speakeasy-api/openapi-generation/pull/1264) is ready. The changes you mentioned are tackled there.

That being said, the version used by the `dotnet` command at compile time is dictated by the `.global.json` file. So I suggest we install .NET8.0 in the Dockerfile before we merge PR#1264

2024-05-16 16:48 UTC, idbentley commented
Makes sense!

2024-05-17 07:49 UTC, TristanSpeakEasy approved these changes

2024-05-17 13:35 UTC, idbentley approved these changes

2024-05-17 13:36 UTC, merged