feat: commit-squash-guidance
speakeasy-api/sdk-generation-action pull request #88
Opened 2024-02-22 01:53 UTC by simplesagar

2024-02-22 01:58 UTC, ryan-timothy-albert approved these changes

2024-02-22 08:53 UTC, TristanSpeakEasy approved these changes

2024-02-22 08:54 UTC, TristanSpeakEasy requested changes
@simplesagar this change has broken the parsing of release info, that will need fixing or your format will need to change to be compatible

2024-04-09 09:46 UTC, simplesagar commented
Reopening

2024-04-09 09:46 UTC, closed without merging